[project]
name = "langraph-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-ollama>=0.3.5",
    "langgraph>=0.5.4",
    "langsmith>=0.4.8",
]
